### ISSUE TITLE
Grades System Needs a Penalty

### ISSUE THREAD

**Issue by kennethshawfriedman** [kennethshawfriedman/uat-site#22]
The current website has two fields for each grade, the grade and the penalty.

The current site only has a spot for the grade.

The steps to complete this:

- Add a new column to the _grades_ table in the DB
- Add a column in the grades_template HTML page
- Add the code to do the math to subtract the penalty from the grade and display that to the student

**Comment by tleng** [comment]
I think Linda was interested in adding to this.  Some thoughts:

>> Actually, several additional columns would be useful:
>>  - a bonus column (e.g. for the chalk talk paper this term)
>>  - a late submission column
>>  - a misc penalties column (for things at end of rubric)
>> Maybe even an additional comment or notes field to log anything?

Thanks!

**Comment by kennethshawfriedman** [comment]
Ok awesome, that sounds great!
